<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<!-- TO JEST JEDYNA SŁUSZNA WERSJA DLA SERWERA SCP -->
		<TargetFramework>net48</TargetFramework>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>
	<ItemGroup>
	  <Reference Include="Assembly-CSharp">
	    <HintPath>..\REFERENCES\Assembly-CSharp.dll</HintPath>
	  </Reference>
	  <Reference Include="Assembly-CSharp-firstpass">
	    <HintPath>..\REFERENCES\Assembly-CSharp-firstpass.dll</HintPath>
	  </Reference>
	  <Reference Include="Exiled.API">
	    <HintPath>..\REFERENCES\Exiled.API.dll</HintPath>
	  </Reference>
	  <Reference Include="Exiled.Events">
	    <HintPath>..\REFERENCES\Exiled.Events.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>..\REFERENCES\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>